### ISSUE TITLE
Error During Processing 

### ISSUE THREAD

**Issue by JohnnyReichel** [DanielSmith1239/HQTriviaMaster#1]
Upon hitting scan, this error occurs.
![screen shot 2017-12-28 at 12 04 46 pm](https://user-images.githubusercontent.com/23438633/34419074-6546cd1c-ebc7-11e7-943b-7c0773799fb3.png)

**Comment by ChrisH10** [comment]
I get the same error.b
<img width="1423" alt="screen shot 2017-12-28 at 8 28 21 pm" src="https://user-images.githubusercontent.com/12632283/34429494-bdf7536e-ec0d-11e7-9189-253203836f41.png">

**Comment by DanielSmith1239** [comment]
Please try updated project.
