### ISSUE TITLE
When there is a question 3 lines long it puts each line in the question as an answer.

### ISSUE THREAD

**Issue by edwardselig** [DanielSmith1239/HQTriviaMaster#10]
It seems to only happen when a question is 3 lines long on my screen (IPhone 5SE).  Lets say the question is
 "what is the
correct answer
to this question?"
The program thinks the choices are

"A. what is the
B. correct answer
C. to this question?"

**Comment by schlossm** [comment]
Could you provide a screenshot for testing purposes? I have an iPhone X so I don't get 3-line questions very often

**Comment by edwardselig** [comment]
actually, i tried recreating it but it seems to not happen every time, but it happens sometimes.  Maybe it's not due to it being 3 lines long but if I find it happening again i'll let you know.

**Comment by schlossm** [comment]
Thank you.  Sometimes the screenshot it takes can be a little funky depending on the Boundary set and it may not catch all the possible answers on screen.  If the issue occurs again, just verify the Boundary is correct, and if it still occurs after that, definitely send a screenshot of the problematic question our way and it'll get figured out.

**Comment by DanielSmith1239** [comment]
This also happens when the player is out of the game. When a player loses, the background color of the option buttons become darker, and there isn't enough contrast between the background and the text for the OCR to read the options.

**Comment by DanielSmith1239** [comment]
Please let me know if the problem persists.
