### ISSUE TITLE
"Unexpectedly Found Nil"

### ISSUE THREAD

**Issue by Jukuu** [DanielSmith1239/HQTriviaMaster#100]
Hi, I am having issues getting the HQ Trivia Master to run. I went through the entire documentation, up to the point of being asked to enter API, id, token etc. and all I got was a pinwheel and a non-responsive program. I closed everything and tried to launch it again, but I am now at a point where the application starts to launch, but keeps bouncing, then just sits there unresponsive. I have tried deleting all of the files and starting fresh, but somehow I can see my ID in the credentials tab within the debug menu. I am so lost and would appreciate any help, but I understand that everyone is busy as well, I am in no hurry. Thanks!

Edit: I know this is the same error found in #66 but I **have** entered my credentials (possibly incorrectly idk).
<img width="1130" alt="screen shot 2018-04-12 at 3 41 58 am" src="https://user-images.githubusercontent.com/7268396/38672922-70914ec4-3e04-11e8-9efa-8db734a0ddf9.png">

**Comment by spaz926** [comment]
Have you ensured you entered your userID with no whitespaces?

**Comment by Jukuu** [comment]
I think that's the mistake I made, I just am in a spot where I don't know how to fix it.

**Comment by Jukuu** [comment]
Okay, I definitely entered the wrong ID I am an idiot.  @DanielSmith1239 how would I reset the program so that the credential prompt appears again? Or how could I edit the incorrect User ID I submitted if that is the route i must take.

**Comment by Jukuu** [comment]
I looked at #103 . In my mac's keychain, I typed in "HQ" and deleted ID and Token entry. I did the same for "Google" and found the constant entries for the API and ID, when rerunning the application it opened perfectly. I wish I wasn't so stupid sometimes.
