### ISSUE TITLE
API Requests Exceeded during single game

### ISSUE THREAD

**Issue by realjamesjones2** [DanielSmith1239/HQTriviaMaster#106]
Google limits you to 100 request per day - when using the Web Socket, it seems to exceed this within a single game.  Is there a way to limit the number of request during the game, or increase the number of API requests?  I've added 3 API keys, and still have the issue - the app responds with 0% 0% and 100% when the limit is exceeded and the 100% option is wrong.

**Comment by Jukuu** [comment]
Yeah, I filled mine with 9 API keys and have never had an issue.
