### ISSUE TITLE
Not Getting the answers

### ISSUE THREAD

**Issue by thysniers** [DanielSmith1239/HQTriviaMaster#107]
When I run either web socket or ocr, it is never able to capture the proper anwsers

**Comment by Jukuu** [comment]
Neither is going to give a 100% accuracy for answers. That's more determined by how you setup your CSE.

WebSocket should not have issues capturing the q&a's text -- if they're not outputting anything at all, that's a different story. Try making your window bigger for OCR and that might help solve that issue.
