### ISSUE TITLE
2 Buildtime issues & mostly 100% 0% 0% answers...

### ISSUE THREAD

**Issue by soup919** [DanielSmith1239/HQTriviaMaster#108]
I have these 2 build time issues for web socket. Wondering if anyone knows how to fix it...
Also when I try OCR it usually gives me 100% 0% 0% answers and occasionally it will work. I check my API usage and do not exceed the 100 per day. Also OCR picks up more when defining the boundary sometimes I see extra letters or numbers in the question or answers.. 
![screen shot 2018-04-16 at 9 34 33 pm](https://user-images.githubusercontent.com/38446554/38843764-8ee71724-41be-11e8-8d8c-e4a2302358b2.png)
Please help thank you.

**Comment by Jukuu** [comment]
Yeah, I'm not sure about the build time issues, I get them as well and it doesn't seem to interfere with the application. 
You should really look through the closed issues before creating a new one. 
Refer to #69 #87 #59 #11 #37 for probability issues.

**Comment by soup919** [comment]
My web socket doesn't work and I set up my proxy and the red box appears and says found web socket.. I dunno what to do. OCR keeps picking up 100% 0% 0% and occasionally works...

**Comment by DanielSmith1239** [comment]
More of an issue with the google api then. There were some other threads here that talked about this issue.
