### ISSUE TITLE
UI Help

### ISSUE THREAD

**Issue by Jukuu** [DanielSmith1239/HQTriviaMaster#109]
Hi, @DanielSmith1239 

I saw one thing on your to-do was improve the UI. I don't have too much experience with programming in swift and wanted to give back for the great work you've done.  If you'd like to work with the UI I came up with, just let me know and I can figure out how to send it to you. 

Here's a short gif of the prototype: 
https://thumbs.gfycat.com/NeedyBeneficialHumpbackwhale-size_restricted.gif

**Comment by DanielSmith1239** [comment]
Thanks! It’s actually more of an issue with how much time I have. I don’t have a lot of time to work on this project, and I like to spend the little time I do have on the actual functionality. Thanks for the idea though!

**Comment by DanielSmith1239** [comment]
Thanks! It’s actually more of an issue with how much time I have. I don’t have a lot of time to work on this project, and I like to spend the little time I do have on the actual functionality. Thanks for the idea though!
