### ISSUE TITLE
Get the best answers out of it

### ISSUE THREAD

**Issue by apates5** [DanielSmith1239/HQTriviaMaster#11]
Hi! I was just playing around with the program and when I was using it most of the time it didn't give an answer because it couldn't find one or it gave an answer and it was wrong. So all I want to know is what websites should I add to my custom search engine to boost my chances of answering the question correct? Thanks!

**Comment by schlossm** [comment]
Right now, the searching is fairly basic.  You are welcome to add whatever websites to your custom engine you want, but until the search strings are generated a little better, they may not help all that much.

Sorry I don't have more for you.  I've begun a longer-term project to try and get smarter searches / results processing but it's a long way off
