### ISSUE TITLE
No account for team and No signing certificate

### ISSUE THREAD

**Issue by lordofthearcade** [DanielSmith1239/HQTriviaMaster#110]
Hello,
I have had no trouble setting up the program until this point. I am getting these two errors even though I have added my Apple Account. What is team "8BE777GSFM", and how would I get the Mac signing certificate. Is it free for 7 days, or is it a 99$/yr charge. Thanks!
<img width="1407" alt="screen shot 2018-04-21 at 1 21 28 pm" src="https://user-images.githubusercontent.com/37389103/39086993-ad1a73ce-4567-11e8-8d1b-040a69057421.png">

**Comment by lordofthearcade** [comment]
Fixed the issue, changed the settings to use my personal account

**Comment by Alex63908** [comment]
I'm having the same issues now how did you change to your personal account?
