### ISSUE TITLE
where is ?? HQTriviaMaster.xcworkspace ??

### ISSUE THREAD

**Issue by pkmuz1** [DanielSmith1239/HQTriviaMaster#111]
i can't find HQTriviaMaster.xcworkspace , some one please help me.    

In HQTriviaMaster.xcworkspace foler there is only one file contents.xcworkspacedata

**Comment by spaz926** [comment]
You need to have Xcode installed to see the folder as a file. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by pkmuz1** [comment]
how to install Xcode in macOS 10.12 without upgrading current version

**Comment by pkmuz1** [comment]
![2018-04-25_040935](https://user-images.githubusercontent.com/31066286/39217654-a4bfab5c-483e-11e8-96da-afd93df832b1.jpg)


Getting error , please help some one step by step.

**Comment by spaz926** [comment]
This program is released as open source code on github for a reason. It is designed and released for developers to play with.

**Comment by spaz926** [comment]
First question is what version of Xcode are you using?

**Comment by pkmuz1** [comment]
xcode version is 8.0 , and i run sudo gem install cocoapods then pod install , pod update
