### ISSUE TITLE
Mitmproxy doesn't work with HQ

### ISSUE THREAD

**Issue by Alex63908** [DanielSmith1239/HQTriviaMaster#114]
when loading HQ up it says error loading schedule and nothing happens in mitmproxy.  Please help Thank you.

**Comment by U-r-Unknown** [comment]
I have working bot which works on all trivia games. No worries about ban as this is PC software. No need of any programming knowledge. If interested mail me onlineuse321@gmail.com. (setting up this is frustrating and it gives answer after time out)

**Comment by FloydRepo** [comment]
did you trust the mitmproxy certificate?
