### ISSUE TITLE
env: /usr/local/bin/convert: No such file or directory

### ISSUE THREAD

**Issue by codeRiding** [DanielSmith1239/HQTriviaMaster#12]
env: /usr/local/bin/convert: No such file or directory
Converted .tif: /var/folders/d9/0y94md311cb0w30rqqby1n4c0000gn/T/hqTriviaMasterTemp.tif
Tesseract Open Source OCR Engine v3.05.01 with Leptonica
Error in fopenReadStream: file not found
Error in findFileFormat: image file not found
Error during processing.

**Comment by schlossm** [comment]
You'll need to install `ImageMagick`.  Try installing that and see if it resolves your issue
