### ISSUE TITLE
Answers are wrong

### ISSUE THREAD

**Issue by Joey0dog** [DanielSmith1239/HQTriviaMaster#13]
My answers are never right I even tested with your hq example

Which one of these is a
cheese?

Piri Piri

Grenadine

Brie

Question type: Which of These
Question search function code: 3

Answers:
Brie: 0
Piri Piri: 0
Grenadine: 1
Predicted Correct Answer: Grenadine
Question type: Which of These
Question search function code: 3

**Comment by schlossm** [comment]
The bot isn't guaranteed to get every question right.  It's the unfortunate reality of a bot such as this one (ones not built on top of strong, highly trained neural networks).  While we're for sure trying to improve the accuracy of results, it's a hard thing to do that'll take time.  I'm sorry for the inconvenience in it, I myself wish I could stick a human encyclopedia into it and get every question right

**Comment by Joey0dog** [comment]
I know but that was the question on your video so I’m not doing anything wrong though?

**Comment by DanielSmith1239** [comment]
Please try the latest version.
