### ISSUE TITLE
Swift Compiler Error

### ISSUE THREAD

**Issue by ituxedo** [DanielSmith1239/HQTriviaMaster#15]
![screen shot 2018-01-15 at 6 57 08 pm](https://user-images.githubusercontent.com/35472565/34965934-f8e966f8-fa25-11e7-8a73-2def60d47231.png)

Using Xcode Version 9.0 beta 2 I receive the following error. I'll revert to the stable branch to test if the error still occurs, but I want to bring this to your attention.

It keeps me from building the application.

**Comment by DanielSmith1239** [comment]
Please try the latest version of HQTriviaMaster and use the latest stable release of Xcode.
