### ISSUE TITLE
I Don't Know How to Fix These Errors. Please Help!

### ISSUE THREAD

**Issue by MatthewH0802** [DanielSmith1239/HQTriviaMaster#16]
https://user-images.githubusercontent.com/35478691/34972204-d2fc144a-fa34-11e7-9fd1-5ed26279ec2d.png 

What can I do to fix them? Btw, am I supposed to press the "Build" button to make the program execute and make that tab that has slots for the question and three questions?

**Comment by DanielSmith1239** [comment]
Please try the following:
1. Navigate to the directory in Terminal.
2. Run `pod install`.
3. Open up the workspace, build and run the project.
