### ISSUE TITLE
"Thread 1: signal SIGABRT" Issue PLEASE HELP!!!!

### ISSUE THREAD

**Issue by roseyg71** [DanielSmith1239/HQTriviaMaster#17]
@DanielSmith1239 I get a "Thread 1: signal SIGABRT" error on line 75 of Shell.swift this forces the app to freeze and become unusable!

**Comment by DanielSmith1239** [comment]
Please try the latest version of HQTriviaMaster.

**Comment by roseyg71** [comment]
@DanielSmith1239  I am still having the same issue with the new version

**Comment by schlossm** [comment]
@roseyg71 can you provide a screenshot of the issue when it freezes?

**Comment by roseyg71** [comment]
<img width="1406" alt="screen shot 2018-01-21 at 5 26 43 pm" src="https://user-images.githubusercontent.com/24533337/35199735-5d48ead4-fed0-11e7-9f77-3779f802f670.png">

**Comment by schlossm** [comment]
Can you expand the console at the bottom right? (with the `terminating with uncaught exception...`)

**Comment by roseyg71** [comment]
here is what is says in full...

2018-01-21 17:29:56.464608-0500 HQ Trivia Master[44622:3451223] [General] An uncaught exception was raised
2018-01-21 17:29:56.464634-0500 HQ Trivia Master[44622:3451223] [General] launch path not accessible
2018-01-21 17:29:56.464694-0500 HQ Trivia Master[44622:3451223] [General] (
	0   CoreFoundation                      0x00007fff57a2600b __exceptionPreprocess + 171
	1   libobjc.A.dylib                     0x00007fff7e5fec76 objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff57ab7c9d +[NSException raise:format:] + 205
	3   Foundation                          0x00007fff59c69de2 -[NSConcreteTask launchWithDictionary:error:] + 1304
	4   HQ Trivia Master                    0x0000000100020d24 _T016HQ_Trivia_Master5ShellC10runCommand33_CE51246001CB53A4F75EC091DC0882CBLLSaySSG6output_AF5errors5Int32V8exitCodetSS3cmd_AF4argsdtFZ + 1220
	5   HQ Trivia Master                    0x0000000100021553 _T016HQ_Trivia_Master5ShellC21checkForRequiredFilesSb10hasConvert_Sb0I9TesseracttyFZ + 227
	6   HQ Trivia Master                    0x000000010002675e _T016HQ_Trivia_Master14ViewControllerC13viewDidAppearyyF + 1118
	7   HQ Trivia Master                    0x0000000100026e54 _T016HQ_Trivia_Master14ViewControllerC13viewDidAppearyyFTo + 36
	8   AppKit                              0x00007fff550b26e2 -[NSViewController _sendViewDidAppear] + 41
	9   AppKit                              0x00007fff550b2407 -[NSView(NSInternal) _windowDidOrderOnScreen] + 67
	10  AppKit                              0x00007fff550b249d -[NSView(NSInternal) _windowDidOrderOnScreen] + 217
	11  AppKit                              0x00007fff558561f1 -[NSWindow _reallyDoOrderWindowAboveOrBelow:relativeTo:findKey:forCounter:force:isModal:] + 2749
	12  AppKit                              0x00007fff550aeb69 -[NSWindow _doOrderWindow:relativeTo:findKey:forCounter:force:isModal:] + 287
	13  AppKit                              0x00007fff550ae9cf -[NSWindow orderWindow:relativeTo:] + 169
	14  AppKit                              0x00007fff551525c1 -[NSWindow makeKeyAndOrderFront:] + 110
	15  QuickLookUI                         0x00007fff6297db31 -[QLSeamlessDocumentOpener showWindow:contentFrame:withBlock:] + 107
	16  AppKit                              0x00007fff551517d6 -[NSWindowController showWindow:] + 718
	17  AppKit                              0x00007fff54f4700d NSApplicationMain + 1047
	18  HQ Trivia Master                    0x0000000100041a2d main + 13
	19  libdyld.dylib                       0x00007fff7f1ee115 start + 1
	20  ???                                 0x0000000000000003 0x0 + 3
)
2018-01-21 17:29:56.465539-0500 HQ Trivia Master[44622:3451223] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'launch path not accessible'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff57a2600b __exceptionPreprocess + 171
	1   libobjc.A.dylib                     0x00007fff7e5fec76 objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff57ab7c9d +[NSException raise:format:] + 205
	3   Foundation                          0x00007fff59c69de2 -[NSConcreteTask launchWithDictionary:error:] + 1304
	4   HQ Trivia Master                    0x0000000100020d24 _T016HQ_Trivia_Master5ShellC10runCommand33_CE51246001CB53A4F75EC091DC0882CBLLSaySSG6output_AF5errors5Int32V8exitCodetSS3cmd_AF4argsdtFZ + 1220
	5   HQ Trivia Master                    0x0000000100021553 _T016HQ_Trivia_Master5ShellC21checkForRequiredFilesSb10hasConvert_Sb0I9TesseracttyFZ + 227
	6   HQ Trivia Master                    0x000000010002675e _T016HQ_Trivia_Master14ViewControllerC13viewDidAppearyyF + 1118
	7   HQ Trivia Master                    0x0000000100026e54 _T016HQ_Trivia_Master14ViewControllerC13viewDidAppearyyFTo + 36
	8   AppKit                              0x00007fff550b26e2 -[NSViewController _sendViewDidAppear] + 41
	9   AppKit                              0x00007fff550b2407 -[NSView(NSInternal) _windowDidOrderOnScreen] + 67
	10  AppKit                              0x00007fff550b249d -[NSView(NSInternal) _windowDidOrderOnScreen] + 217
	11  AppKit                              0x00007fff558561f1 -[NSWindow _reallyDoOrderWindowAboveOrBelow:relativeTo:findKey:forCounter:force:isModal:] + 2749
	12  AppKit                              0x00007fff550aeb69 -[NSWindow _doOrderWindow:relativeTo:findKey:forCounter:force:isModal:] + 287
	13  AppKit                              0x00007fff550ae9cf -[NSWindow orderWindow:relativeTo:] + 169
	14  AppKit                              0x00007fff551525c1 -[NSWindow makeKeyAndOrderFront:] + 110
	15  QuickLookUI                         0x00007fff6297db31 -[QLSeamlessDocumentOpener showWindow:contentFrame:withBlock:] + 107
	16  AppKit                              0x00007fff551517d6 -[NSWindowController showWindow:] + 718
	17  AppKit                              0x00007fff54f4700d NSApplicationMain + 1047
	18  HQ Trivia Master                    0x0000000100041a2d main + 13
	19  libdyld.dylib                       0x00007fff7f1ee115 start + 1
	20  ???                                 0x0000000000000003 0x0 + 3
)
libc++abi.dylib: terminating with uncaught exception of type NSException

**Comment by schlossm** [comment]
Okay, so two things here.  One, it looks like you don't have tesseract or imagemagick installed properly.   Two, I'll need to fix it real fast to make sure it doesn't crash like this.  It isn't supposed to crash if the launch path doesn't exist but something is improperly catching

**Comment by schlossm** [comment]
PR #18 resolves this issue.

**Comment by roseyg71** [comment]
Thanks so much, I have been trying to fix this for a while and it finally works!
