### ISSUE TITLE
Problem with Building the project

### ISSUE THREAD

**Issue by flynncupitt** [DanielSmith1239/HQTriviaMaster#19]
I am getting this error when trying to build in Xcode:
Apple Mach-O Linker (Id) error
Linker command failed with exit code 1 (use -v to see invocation)

I have no idea what to do to fix this...
![screen shot 2018-01-22 at 7 29 41 pm](https://user-images.githubusercontent.com/35675407/35207976-b0cad944-ffaa-11e7-9cfa-b88081fef7e7.png)

**Comment by schlossm** [comment]
Hi @flynncupitt 

Please run `pod install` in Terminal while in the project's directory.   Then, please use the `.xcworkspace` file to build the project
