### ISSUE TITLE
No Answer to Question

### ISSUE THREAD

**Issue by flynncupitt** [DanielSmith1239/HQTriviaMaster#21]
Everything seems to work fine in the program, it scans, inputs the question, i click "stop scanning" and then when i click answer, it never shows which one it is...

(Yes I have put in an API key & a search engine ID.

**Comment by roseyg71** [comment]
@flynncupitt try this image...
<img width="679" alt="test" src="https://user-images.githubusercontent.com/24533337/35252265-a222025c-ffad-11e7-9441-0fff4223a3b0.png">

**Comment by flynncupitt** [comment]
Ive just un installed it to try to re install it but it won't let me run "pod install"

**Comment by roseyg71** [comment]
what error are you getting when you run pod install?

**Comment by flynncupitt** [comment]
Well, I've just updated to High Sierra and its something about the ruby framework?

**Comment by flynncupitt** [comment]
pods are installing now, i just re installed cocoapods

**Comment by roseyg71** [comment]
Just so you know there is a website http://hquack.com/ that answers hq questions in the live game and it works really well

**Comment by flynncupitt** [comment]
but idk why i wasn't getting the answer in the first place... it must have been something to do with the search engine ID or API key...
