### ISSUE TITLE
Accuracy not very good...

### ISSUE THREAD

**Issue by flynncupitt** [DanielSmith1239/HQTriviaMaster#22]
Ive got it working, but for most of the questions, it has gotten it wrong, either because it found the wrong answer, or it didn't get the correct text...

Any ways to fix?

**Comment by DanielSmith1239** [comment]
To fix the text issue, make sure the boundary you define fully contains the question and all of the options. Regarding the accuracy, this program is a work of progress. Feel free to play around with adding different websites, such as wikipedia, to the list of websites to search in your Google custom search page.

**Comment by flynncupitt** [comment]
Thanks, still quite in accurate, but a great start! :D
