### ISSUE TITLE
Script Doesn't Return Answers

### ISSUE THREAD

**Issue by xxhomelandefensexx** [DanielSmith1239/HQTriviaMaster#25]
This is what happens:

<img width="1280" alt="screen shot 2018-01-26 at 4 58 30 pm" src="https://user-images.githubusercontent.com/35853180/35462585-93868b0e-02ba-11e8-8682-2927fa59a06e.png">

Not sure what/how to fix this, just wanted to report it.

**Comment by schlossm** [comment]
Are you able to type in that question + answers, Hit `Answer`, and then copy and paste the whole log Xcode gives you?

**Comment by bradtaylor64** [comment]
how did you install the pods

**Comment by xxhomelandefensexx** [comment]
Here is the log.

2018-01-26 16:44:58.407531-0500 HQ Trivia Master[24148:9307247] MessageTracer: Falling back to default whitelist
Mouse Pressed Down
Mouse Released
(910.84375, 325.7421875, 348.171875, 312.171875)
Tesseract Open Source OCR Engine v3.05.01 with Leptonica
Page 1
The audio equipment term 'hi fi' is short for what?
Hippo Fitting
Hilarious Fiction
High Fidelity
Question type: End What
Question search function code: 15
Search String: The audio equipment term 'hi fi' is short for what? Hippo Fitting
Search String: The audio equipment term 'hi fi' is short for what? Hilarious Fiction
Search String: The audio equipment term 'hi fi' is short for what? High Fidelity
2018-01-26 16:45:15.250007-0500 HQ Trivia Master[24148:9308826] [BoringSSL] Function boringssl_context_get_peer_sct_list: line 1757 received sct extension length is less than sct data length
Search String: The audio equipment term 'hi fi' is short for what? Hippo Fitting
Search String: The audio equipment term 'hi fi' is short for what? Hilarious Fiction
Search String: The audio equipment term 'hi fi' is short for what? High Fidelity

Answers:
Hilarious Fiction: 0
Hippo Fitting: 0
High Fidelity: 0
Predicted Correct Answer: 
Tesseract Open Source OCR Engine v3.05.01 with Leptonica
Page 1
The audio equipment term 'hi fi' is short for what?
Hippo Fitting
Hilarious Fiction
High Fidelity
Question type: End What
Question search function code: 15
Search String: The audio equipment term 'hi fi' is short for what? Hippo Fitting
Search String: The audio equipment term 'hi fi' is short for what? Hilarious Fiction
Search String: The audio equipment term 'hi fi' is short for what? High Fidelity
Search String: The audio equipment term 'hi fi' is short for what? Hippo Fitting
Search String: The audio equipment term 'hi fi' is short for what? Hilarious Fiction
Search String: The audio equipment term 'hi fi' is short for what? High Fidelity

Answers:
Hippo Fitting: 0
Hilarious Fiction: 0
High Fidelity: 0
Predicted Correct Answer: 
Tesseract Open Source OCR Engine v3.05.01 with Leptonica
Page 1
The audio equipment term 'hi fi' is short for what?
Hippo Fitting
Hilarious Fiction
High Fidelity
Question type: End What
Question search function code: 15
Search String: The audio equipment term 'hi fi' is short for what? Hippo Fitting
Search String: The audio equipment term 'hi fi' is short for what? Hilarious Fiction
Search String: The audio equipment term 'hi fi' is short for what? High Fidelity
Search String: The audio equipment term 'hi fi' is short for what? Hippo Fitting
Search String: The audio equipment term 'hi fi' is short for what? Hilarious Fiction
Search String: The audio equipment term 'hi fi' is short for what? High Fidelity

Answers:
Hilarious Fiction: 0
Hippo Fitting: 0
High Fidelity: 0
Predicted Correct Answer: 
Tesseract Open Source OCR Engine v3.05.01 with Leptonica
Page 1
The audio equipment term 'hi fi' is short for what?
Hippo Fitting
Hilarious Fiction
High Fidelity
Question type: End What
Question search function code: 15
Search String: The audio equipment term 'hi fi' is short for what? Hippo Fitting
Search String: The audio equipment term 'hi fi' is short for what? Hilarious Fiction
Search String: The audio equipment term 'hi fi' is short for what? High Fidelity
Search String: The audio equipment term 'hi fi' is short for what? Hippo Fitting
Search String: The audio equipment term 'hi fi' is short for what? Hilarious Fiction
Search String: The audio equipment term 'hi fi' is short for what? High Fidelity

Answers:
Hilarious Fiction: 0
Hippo Fitting: 0
High Fidelity: 0
Predicted Correct Answer: 
Tesseract Open Source OCR Engine v3.05.01 with Leptonica
Page 1
The audio equipment term 'hi fi' is short for what?
Hippo Fitting
Hilarious Fiction
High Fidelity
Question type: End What
Question search function code: 15
Search String: The audio equipment term 'hi fi' is short for what? Hippo Fitting
Search String: The audio equipment term 'hi fi' is short for what? Hilarious Fiction
Search String: The audio equipment term 'hi fi' is short for what? High Fidelity
Search String: The audio equipment term 'hi fi' is short for what? Hippo Fitting
Search String: The audio equipment term 'hi fi' is short for what? Hilarious Fiction
Search String: The audio equipment term 'hi fi' is short for what? High Fidelity

Answers:
Hippo Fitting: 0
Hilarious Fiction: 0
High Fidelity: 0
Predicted Correct Answer: 
2018-01-26 16:49:15.278324-0500 HQ Trivia Master[24148:9318973] TIC Read Status [1:0x0]: 1:57
2018-01-26 16:49:15.279644-0500 HQ Trivia Master[24148:9318973] TIC Read Status [1:0x0]: 1:57
Question type: End What
Question search function code: 15
Search String: The audio equipment term 'hi fi' is short for what? Hippo Fitting
Search String: The audio equipment term 'hi fi' is short for what? Hilarious Fiction
Search String: The audio equipment term 'hi fi' is short for what? High Fidelity
Search String: The audio equipment term 'hi fi' is short for what? Hippo Fitting
Search String: The audio equipment term 'hi fi' is short for what? Hilarious Fiction
Search String: The audio equipment term 'hi fi' is short for what? High Fidelity

Answers:
Hilarious Fiction: 0
Hippo Fitting: 0
High Fidelity: 0
Predicted Correct Answer: 
Tesseract Open Source OCR Engine v3.05.01 with Leptonica
Page 1
The audio equipment term 'hi fi' is short for what?
Hippo Fitting
Hilarious Fiction
High Fidelity
Question type: End What
Question search function code: 15
Search String: The audio equipment term 'hi fi' is short for what? Hippo Fitting
Search String: The audio equipment term 'hi fi' is short for what? Hilarious Fiction
Search String: The audio equipment term 'hi fi' is short for what? High Fidelity
Search String: The audio equipment term 'hi fi' is short for what? Hippo Fitting
Search String: The audio equipment term 'hi fi' is short for what? Hilarious Fiction
Search String: The audio equipment term 'hi fi' is short for what? High Fidelity

Answers:
Hippo Fitting: 0
Hilarious Fiction: 0
High Fidelity: 0
Predicted Correct Answer: 
2018-01-26 16:55:38.528884-0500 HQ Trivia Master[24148:9330716] TIC Read Status [2:0x0]: 1:57
2018-01-26 16:55:38.528935-0500 HQ Trivia Master[24148:9330716] TIC Read Status [2:0x0]: 1:57
Tesseract Open Source OCR Engine v3.05.01 with Leptonica
Page 1
The audio equipment term 'hi fi' is short for what?
Hippo Fitting
Hilarious Fiction
High Fidelity
Question type: End What
Question search function code: 15
Search String: The audio equipment term 'hi fi' is short for what? Hippo Fitting
Search String: The audio equipment term 'hi fi' is short for what? Hilarious Fiction
Search String: The audio equipment term 'hi fi' is short for what? High Fidelity
Search String: The audio equipment term 'hi fi' is short for what? Hippo Fitting
Search String: The audio equipment term 'hi fi' is short for what? Hilarious Fiction
Search String: The audio equipment term 'hi fi' is short for what? High Fidelity

Answers:
Hilarious Fiction: 0
Hippo Fitting: 0
High Fidelity: 0
Predicted Correct Answer: 
Tesseract Open Source OCR Engine v3.05.01 with Leptonica
Page 1
Empty page!!
Empty page!!
Did not find question end
Tesseract Open Source OCR Engine v3.05.01 with Leptonica
Page 1
Empty page!!
Empty page!!
Did not find question end
Tesseract Open Source OCR Engine v3.05.01 with Leptonica
Page 1
Empty page!!
Empty page!!
Did not find question end
Tesseract Open Source OCR Engine v3.05.01 with Leptonica
Page 1
Empty page!!
Empty page!!
Did not find question end
Tesseract Open Source OCR Engine v3.05.01 with Leptonica
Page 1
Empty page!!
Empty page!!
Did not find question end
Tesseract Open Source OCR Engine v3.05.01 with Leptonica
Page 1
Empty page!!
Empty page!!
Did not find question end
Tesseract Open Source OCR Engine v3.05.01 with Leptonica
Page 1
Empty page!!
Empty page!!
Did not find question end
Tesseract Open Source OCR Engine v3.05.01 with Leptonica
Page 1
Empty page!!
Empty page!!
Did not find question end
Tesseract Open Source OCR Engine v3.05.01 with Leptonica
Page 1
Empty page!!
Empty page!!
Did not find question end
Tesseract Open Source OCR Engine v3.05.01 with Leptonica
Page 1
Empty page!!
Empty page!!
Did not find question end
Tesseract Open Source OCR Engine v3.05.01 with Leptonica
Page 1
Empty page!!
Empty page!!
Did not find question end
Tesseract Open Source OCR Engine v3.05.01 with Leptonica
Page 1
Empty page!!
Empty page!!
Did not find question end
Tesseract Open Source OCR Engine v3.05.01 with Leptonica
Page 1
Empty page!!
Empty page!!
Did not find question end
Tesseract Open Source OCR Engine v3.05.01 with Leptonica
Page 1
Empty page!!
Empty page!!
Did not find question end
Tesseract Open Source OCR Engine v3.05.01 with Leptonica
Page 1
Empty page!!
Empty page!!
Did not find question end
Tesseract Open Source OCR Engine v3.05.01 with Leptonica
Page 1
Empty page!!
Empty page!!
Did not find question end
Tesseract Open Source OCR Engine v3.05.01 with Leptonica
Page 1
Empty page!!
Empty page!!
Did not find question end
Tesseract Open Source OCR Engine v3.05.01 with Leptonica
Page 1
Empty page!!
Empty page!!
Did not find question end
Tesseract Open Source OCR Engine v3.05.01 with Leptonica
Page 1
Empty page!!
Empty page!!
Did not find question end
Tesseract Open Source OCR Engine v3.05.01 with Leptonica
Page 1
Empty page!!
Empty page!!
Did not find question end
Tesseract Open Source OCR Engine v3.05.01 with Leptonica
Page 1
Did not find question end
Tesseract Open Source OCR Engine v3.05.01 with Leptonica
Page 1
The audio equipment term 'hi fi' is short for what?
Hippo Fitting
Hilarious Fiction
High Fidelity
Question type: End What
Question search function code: 15
Search String: The audio equipment term 'hi fi' is short for what? Hippo Fitting
Search String: The audio equipment term 'hi fi' is short for what? Hilarious Fiction
Search String: The audio equipment term 'hi fi' is short for what? High Fidelity
Search String: The audio equipment term 'hi fi' is short for what? Hippo Fitting
Search String: The audio equipment term 'hi fi' is short for what? Hilarious Fiction
Search String: The audio equipment term 'hi fi' is short for what? High Fidelity

Answers:
Hilarious Fiction: 0
Hippo Fitting: 0
High Fidelity: 0
Predicted Correct Answer: 
Tesseract Open Source OCR Engine v3.05.01 with Leptonica
Page 1
The audio equipment term 'hi fi' is short for what?
Hippo Fitting
Hilarious Fiction
High Fidelity
Question type: End What
Question search function code: 15
Search String: The audio equipment term 'hi fi' is short for what? Hippo Fitting
Search String: The audio equipment term 'hi fi' is short for what? Hilarious Fiction
Search String: The audio equipment term 'hi fi' is short for what? High Fidelity
Search String: The audio equipment term 'hi fi' is short for what? Hippo Fitting
Search String: The audio equipment term 'hi fi' is short for what? Hilarious Fiction
Search String: The audio equipment term 'hi fi' is short for what? High Fidelity

Answers:
Hippo Fitting: 0
Hilarious Fiction: 0
High Fidelity: 0
Predicted Correct Answer: 
Tesseract Open Source OCR Engine v3.05.01 with Leptonica
Page 1
The audio equipment term 'hi fi' is short for what?
Hippo Fitting
Hilarious Fiction
High Fidelity
Question type: End What
Question search function code: 15
Search String: The audio equipment term 'hi fi' is short for what? Hippo Fitting
Search String: The audio equipment term 'hi fi' is short for what? Hilarious Fiction
Search String: The audio equipment term 'hi fi' is short for what? High Fidelity
Search String: The audio equipment term 'hi fi' is short for what? Hippo Fitting
Search String: The audio equipment term 'hi fi' is short for what? Hilarious Fiction
Search String: The audio equipment term 'hi fi' is short for what? High Fidelity

Answers:
Hilarious Fiction: 0
Hippo Fitting: 0
High Fidelity: 0
Predicted Correct Answer: 
Tesseract Open Source OCR Engine v3.05.01 with Leptonica
Page 1
The audio equipment term 'hi fi' is short for what?
Hippo Fitting
Hilarious Fiction
High Fidelity
Question type: End What
Question search function code: 15
Search String: The audio equipment term 'hi fi' is short for what? Hippo Fitting
Search String: The audio equipment term 'hi fi' is short for what? Hilarious Fiction
Search String: The audio equipment term 'hi fi' is short for what? High Fidelity
Search String: The audio equipment term 'hi fi' is short for what? Hippo Fitting
Search String: The audio equipment term 'hi fi' is short for what? Hilarious Fiction
Search String: The audio equipment term 'hi fi' is short for what? High Fidelity

Answers:
Hippo Fitting: 0
Hilarious Fiction: 0
High Fidelity: 0
Predicted Correct Answer: 
2018-01-26 17:01:14.438144-0500 HQ Trivia Master[24148:9343396] TIC Read Status [3:0x0]: 1:57
2018-01-26 17:01:14.438187-0500 HQ Trivia Master[24148:9343396] TIC Read Status [3:0x0]: 1:57
Tesseract Open Source OCR Engine v3.05.01 with Leptonica
Page 1
The audio equipment term 'hi fi' is short for what?
Hippo Fitting
Hilarious Fiction
High Fidelity
Question type: End What
Question search function code: 15
Search String: The audio equipment term 'hi fi' is short for what? Hippo Fitting
Search String: The audio equipment term 'hi fi' is short for what? Hilarious Fiction
Search String: The audio equipment term 'hi fi' is short for what? High Fidelity
Search String: The audio equipment term 'hi fi' is short for what? Hippo Fitting
Search String: The audio equipment term 'hi fi' is short for what? Hilarious Fiction
Search String: The audio equipment term 'hi fi' is short for what? High Fidelity

Answers:
Hippo Fitting: 0
Hilarious Fiction: 0
High Fidelity: 0
Predicted Correct Answer: 
Tesseract Open Source OCR Engine v3.05.01 with Leptonica
Page 1
The audio equipment term 'hi fi' is short for what?
Hippo Fitting
Hilarious Fiction
High Fidelity
Question type: End What
Question search function code: 15
Search String: The audio equipment term 'hi fi' is short for what? Hippo Fitting
Search String: The audio equipment term 'hi fi' is short for what? Hilarious Fiction
Search String: The audio equipment term 'hi fi' is short for what? High Fidelity
Search String: The audio equipment term 'hi fi' is short for what? Hippo Fitting
Search String: The audio equipment term 'hi fi' is short for what? Hilarious Fiction
Search String: The audio equipment term 'hi fi' is short for what? High Fidelity

Answers:
Hippo Fitting: 0
Hilarious Fiction: 0
High Fidelity: 0
Predicted Correct Answer: 
Tesseract Open Source OCR Engine v3.05.01 with Leptonica
Page 1
The audio equipment term 'hi fi' is short for what?
Hippo Fitting
Hilarious Fiction
High Fidelity
Question type: End What
Question search function code: 15
Search String: The audio equipment term 'hi fi' is short for what? Hippo Fitting
Search String: The audio equipment term 'hi fi' is short for what? Hilarious Fiction
Search String: The audio equipment term 'hi fi' is short for what? High Fidelity
Search String: The audio equipment term 'hi fi' is short for what? Hippo Fitting
Search String: The audio equipment term 'hi fi' is short for what? Hilarious Fiction
Search String: The audio equipment term 'hi fi' is short for what? High Fidelity

Answers:
Hippo Fitting: 0
Hilarious Fiction: 0
High Fidelity: 0
Predicted Correct Answer: 
Question type: End What
Question search function code: 15
Search String: The audio equipment term 'hi fi' is short for what? Hippo Fitting
Search String: The audio equipment term 'hi fi' is short for what? Hilarious Fiction
Search String: The audio equipment term 'hi fi' is short for what? High Fidelity
Search String: The audio equipment term 'hi fi' is short for what? Hippo Fitting
Search String: The audio equipment term 'hi fi' is short for what? Hilarious Fiction
Search String: The audio equipment term 'hi fi' is short for what? High Fidelity

Answers:
Hilarious Fiction: 0
Hippo Fitting: 0
High Fidelity: 0
Predicted Correct Answer:

**Comment by xxhomelandefensexx** [comment]
Had it open and running for a while, so some of that might be old.

**Comment by DanielSmith1239** [comment]
Similar to issue #33.
