### ISSUE TITLE
not returning answers

### ISSUE THREAD

**Issue by tanking2113** [DanielSmith1239/HQTriviaMaster#27]
i believe there might be an issue with the search engine/api however when i click define boundary and it scans the questions it returns no answer and i see other people have had a similar issue

**Comment by schlossm** [comment]
Make sure you've at least added `www.google.com` under the Search Sites (may not need to do this).  Also, if you've signed up for the basic CSE, you'll have a hard limit on the number of searches you can do at a time.  Please also verify your CSE is verified (they'll have emailed you a link)

**Comment by DanielSmith1239** [comment]
You shouldn’t need to add google if you make sure it is searching the entire web (there is a drop down menu in the settings by the Search Sites section).
