### ISSUE TITLE
What is the Setup Code

### ISSUE THREAD

**Issue by Hulapopper** [DanielSmith1239/HQTriviaMaster#30]

**Comment by schlossm** [comment]
What do you mean by "Setup Code?" If you're talking about the Search Engine API & Key then please look at the README as it provides the link to go obtain the keys

**Comment by Hulapopper** [comment]
How do you get to the part where you put in the search engine API and Key. Is that in Xcode or in the Trivia Master Application because I am having issues opening the Trivia Master Application. Xcode can successfully build the Trivia Master but when it tries to open a message pops up in the bottom left corner saying Trivia Master[26808:444024] Unknown Window class (null) in Interface Builder file, creating generic Window instead

**Comment by schlossm** [comment]
When the application runs for the first time, it'll automatically prompt for the ID and Key.  If you ever need to change this, you can go to `HQTriviaMaster > Preferences`
