### ISSUE TITLE
Trivia Master will not open it says at the bottom 2018-01-28 15:15:35.406538-0500 Trivia Master[18849:253108] Unknown Window class (null) in Interface Builder file creating generic Window instead

### ISSUE THREAD

**Issue by Hulapopper** [DanielSmith1239/HQTriviaMaster#31]
HELP

**Comment by Hulapopper** [comment]
I am not sure what caused the issue and I am using Xcode version 9.2

**Comment by Hulapopper** [comment]
Also, how do you run pod install while in Project directory? I try and open the project for Xcode then open terminal and put in pod install and it always comes back with 'Podfile' not in project directory. Can you please give me some kind of direction on how to do this. I really appreciate all of the help thank you

**Comment by Hulapopper** [comment]
Alright I have figured out how to download the pods and now it says I have 3 issues
1. CurrentDirectoryURL is only available OSX 13 or newer          (I have the latest 10.12.6 high sierra update)
2. Command /usr/bin/ditto failed with exit code 1
3. clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by schlossm** [comment]
Hi @Hulapopper, please check out PR #35 and let me know if that resolves the issue with the NSWindow.  I have no problems building in Xcode 9.2.

For the Pods: open Terminal, and type `cd /path/to/HQTriviaMaster-master/`, then run `pod install`

**Comment by Hulapopper** [comment]
THANK YOU

**Comment by Hulapopper** [comment]
When I go to my custom search engine I am able to find the Search engine ID but can you tell me what the API key is

**Comment by Hulapopper** [comment]
Ok, I figured out how to get the API key and now I am assuming I just define the boundary and then press answer.

**Comment by Hulapopper** [comment]
Now it won't scan the boundary I have selected is there anything I need to do to correct this.

**Comment by Hulapopper** [comment]
Now It defines the boundary and when I click scan Xcode pops up and shows me like 5 or 6 breakpoints

**Comment by Hulapopper** [comment]
FINALLY, I DELETED EVERYTHING AND REINSTALLED WITH SIP OFF AND IT WORKED IT IS 100% SUCCESSFULLY RUNNING.

THANK YOU FOR ALL THE HELP
