### ISSUE TITLE
Result hits going down after questions

### ISSUE THREAD

**Issue by michael-bateman** [DanielSmith1239/HQTriviaMaster#33]
After the first 5 or 6 questions, the program spits out fewer and fewer searh results therefore being somewhat inaccurate. How can I combat this? The next day I will go back and the same question the previous day that gave me 1 result now is accurate with 30-40 results.

**Comment by DanielSmith1239** [comment]
By default, Google doesn’t give you a lot of searches with the API. You need to go into the settings and set the number of requests allowed to a bigger number.

**Comment by kokirikat** [comment]
Which settings do you mean? CSE settings? I don't see where they allow us to do more than 100 requests a day since we're on the free version.

**Comment by michael-bateman** [comment]
@DanielSmith1239 How do I add more requests?

**Comment by DanielSmith1239** [comment]
@schlossm Do you have the link for the control panel where they could set this up? I can’t seem to find it.

**Comment by michael-bateman** [comment]
Hmm, I just tested it out and noticed that if you switch the API key after every few questions ONLY and not the ID then it works perfectly fine. Would you be able to create an option where you could add multiple API keys then it could switch after like every 2 or 3 questions?
