### ISSUE TITLE
Log is not predicting an answer

### ISSUE THREAD

**Issue by ItsCresent** [DanielSmith1239/HQTriviaMaster#36]
Hey there i just got this working on a VM and decided to test it on a yt video of a past game. It picked up all the questions fine and answers but im confused about how i know what answer is correct as in the log where it says predicted answer: its blank and answer: is blank also.

**Comment by robertsmith7** [comment]
Could you send screenshots so we can help resolve the issue? I'm struggling to understand what the exact issue is.

**Comment by schlossm** [comment]
Hi @ItsCresent, did you properly activate your Google CSE? Please be aware you'll also have a daily limit of 100 searches, after which it returns no data

**Comment by ItsCresent** [comment]
@robertsmith7 
![screenshot_57](https://user-images.githubusercontent.com/29209844/35626635-39480884-068e-11e8-928d-f4389771bef1.png)

**Comment by schlossm** [comment]
Your CSE isn't returning the app any data.  Check to make sure it's activated and that it is searching at least "www.google.com"
