### ISSUE TITLE
Why is the scan so bad at reading the question??? Almost 100% of the time it is wrong.

### ISSUE THREAD

**Issue by Hulapopper** [DanielSmith1239/HQTriviaMaster#37]

**Comment by schlossm** [comment]
I've generally found that the smaller the window, the more incorrect Tesseract becomes.  If you try making the window larger, does it get better?

**Comment by Hulapopper** [comment]
that is what I thought so I stretched it out to the maximum size of my
screen but it did not fix the issue. Another thing I wanted to ask is if it
100% necessary to pay for the API because this free version API that I have
wears off pretty quick. After like the 5th or 6th question your on your own
because at that point it is only coming back with like one or two searches.

**Comment by schlossm** [comment]
Hmmm that wouldn't be a terrible idea to do.  Allow you to enter multiple CSEs that'll auto switch if the daily limit is hit.

Will you record your screen doing the process of setting up the boundary and scanning? I'd like to see what's going on there to help resolve this

**Comment by Hulapopper** [comment]
I am making it as large as my screen is and it still does a bad job

**Comment by Hulapopper** [comment]
hello

**Comment by schlossm** [comment]
Without seeing a video of what you’re doing in action, I can’t troubleshoot much further.  I personally have no issues with scanning unless the correct answer is showing.

Other than making sure the boundary goes over the question and answers with some border around them, there isn’t much more you can do.  Tesseract is finicky

**Comment by Hulapopper** [comment]
you didn't get my video sorry I didn't see that it failed to send let me
give it another try

**Comment by schlossm** [comment]
Hi @Hulapopper, it seems the video still did not upload properly.  GitHub must not like sending videos through email, can you upload it directly here?

**Comment by Hulapopper** [comment]
Here is the Third Try

**Comment by DanielSmith1239** [comment]
Didn't work. Try uploading to a different site and posting the link.

**Comment by DanielSmith1239** [comment]
Working on an update that uses he HQ web socket to get the questions, eliminating the need for the OCR.

**Comment by Hulapopper** [comment]
good idea

On Feb 20, 2018 12:39 PM, "Dani Smith" <notifications@github.com> wrote:

Working on an update that uses he HQ web socket to get the questions,
eliminating the need for the OCR.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/DanielSmith1239/HQTriviaMaster/issues/37#issuecomment-367057205>,
or mute the thread
