### ISSUE TITLE
Not being prompted to put in API key or id

### ISSUE THREAD

**Issue by CheetosBreak** [DanielSmith1239/HQTriviaMaster#39]
when running HQTriviaMaster.xcworkspace for the first time I am not prompted to put either information instead it just brings me here, https://gyazo.com/0871c90e6766770e8b9a4915cb9eed66
If i could have some assistance to fix this I would greatly appreciate it.

**Comment by schlossm** [comment]
Hi @CheetosBreak, you will need to install the Pods first!  You can do this be either (Downloading CocoaPods)[https://cocoapods.org/app] or using terminal to run `pod install` in HQTriviaMaster's directory

**Comment by CheetosBreak** [comment]
Thank you @schlossm but every time I try to run the pod install in terminal i get "-bash: pod: command not found"  I even downloaded CocoaPods and Im still getting the same issue as before, am I missing something, thank you so much for the help

**Comment by schlossm** [comment]
Hi @CheetosBreak, an FAQ was recently added to the README.  In it, several links and troubleshooting steps are presented.  Please make sure your CSE is activated.  You may also need to add `https://www.google.com` to your Sites to Search for full functionality.
