### ISSUE TITLE
stuck after doing pod install in TriviaMaster directory

### ISSUE THREAD

**Issue by Heros15582** [DanielSmith1239/HQTriviaMaster#40]
I installed cocoapods and ran pod install inside HQTriviaMaster directory. i am unsure what the next step would be. If it has to do with building the application i am unsure on how to accomplish this.

I added an image of my directory to make sure i didn't skip anything
![capture](https://user-images.githubusercontent.com/15828577/35835583-7d4e2c24-0aa9-11e8-803e-e2843720edbe.PNG)

**Comment by DanielSmith1239** [comment]
Open the xcworkspace in Xcode, and build and run the application from there.
