### ISSUE TITLE
After getting out of the game, the OCR does not work

### ISSUE THREAD

**Issue by michael-bateman** [DanielSmith1239/HQTriviaMaster#42]
After getting out in the game, OCR does not work to grab the answers - the question is grabbed fine. I believe the issue is that once you are out, the answers have a grey background, therefore not allowing the OCR to grab the answers. Is there any fix on this?

**Comment by DanielSmith1239** [comment]
Nope. You answered your own question. Maybe in the future we could remove the background color from the image before running the OCR, but nothing is in the works.
