### ISSUE TITLE
WebSocket

### ISSUE THREAD

**Issue by gjacobs314** [DanielSmith1239/HQTriviaMaster#44]
I made a little version of this that goes and gets questions + possible answers from the WebSocket, but I haven't added the searching/answering part of it. If there was any way of contacting you maybe we could talk about working on it together?

**Comment by DanielSmith1239** [comment]
Sure, I was actually looking into this. Want to shoot me an email with the details? dani@danismithproductions.com

**Comment by gjacobs314** [comment]
Alright, sent an email.

**Comment by DanielSmith1239** [comment]
In communication.
