### ISSUE TITLE
Websocket) Build succeeded but warnings?

### ISSUE THREAD

**Issue by cloudydesigns** [DanielSmith1239/HQTriviaMaster#47]
<img width="1085" alt="screen shot 2018-02-26 at 17 17 49" src="https://user-images.githubusercontent.com/36579687/36684718-224b2702-1b19-11e8-9136-7ab557301409.png">

Program still ran and i entered my details. Not sure if it's bad.

Also 2 other questions:
1) I reopened preferences after entering everything, it was empty so does it mean I have to redo it
2) In the readme it says to save user ID but there was no place to put it, what should I do with it.

**Comment by cloudydesigns** [comment]
<img width="706" alt="screen shot 2018-02-26 at 17 25 44" src="https://user-images.githubusercontent.com/36579687/36685051-1d265b92-1b1a-11e8-897b-27d3e2d76e1e.png">

I assumed username was my actual username, not the user ID.
Also would the warnings affect anything?

**Comment by michael-bateman** [comment]
How can I find my HQ Token?

**Comment by DanielSmith1239** [comment]
The instructions are in the ReadMe.

**Comment by kyleinprogress** [comment]
May want to clean up the instructions a little bit. The part about entering the token is a little misleading.

The whole token actually includes "Bearer a bunch of random characters". When you step through the code, "Bearer is already there, so you actually need all the text EXCLUDING Bearer. Just a little confusing if you're running this for the first time.

**Comment by DanielSmith1239** [comment]
Actually, if you REALLY look at the code, you’ll see that it checks whether or not the user-entered token contains “Bearer”, and only adds it if the user didn’t include it.

**Comment by DanielSmith1239** [comment]
Shit, I actually just checked and I forgot to implement that check in one of the files. I’ll fix it at some point tomorrow hopefully.

**Comment by DanielSmith1239** [comment]
The check is in the web socket manager, not the connection controller. I’ll hopefully add the check to the connection controller later today or tomorrow.
