### ISSUE TITLE
Is this normal? Also how do you get to HQTriviaMaster preferences?

### ISSUE THREAD

**Issue by Arithemus** [DanielSmith1239/HQTriviaMaster#48]
![screen shot 2018-02-26 at 7 14 53 pm](https://user-images.githubusercontent.com/36869480/36705162-650abcaa-1b29-11e8-848c-400e0b101e69.png)
![screen shot 2018-02-26 at 7 09 53 pm](https://user-images.githubusercontent.com/36869480/36705093-0c9c1bf4-1b29-11e8-98d4-825bd5f7e74e.png)

The First picture is what comes up when I press start... What am I doing wrong? I don't know what that is and can someone else tell me where the preferences are so I can put my user id and token in? Thanks
![screen shot 2018-02-26 at 7 16 21 pm](https://user-images.githubusercontent.com/36869480/36705209-8bed466c-1b29-11e8-84b9-0f6015c9d136.png)
![screen shot 2018-02-26 at 7 16 06 pm](https://user-images.githubusercontent.com/36869480/36705211-8fb17958-1b29-11e8-9fb0-469a9b4e1ca0.png)

Here are the pictures of the pod stuff, I am pretty sure I installed it.

**Comment by Arithemus** [comment]
I don't think I put in the google API maybe thats whats up

**Comment by DanielSmith1239** [comment]
...you need to add your certificate. Click on the project in the sidebar.

**Comment by cloudydesigns** [comment]
![image](https://user-images.githubusercontent.com/36579687/36705520-8938a928-1b5d-11e8-8a9d-eae9f9be3ef4.png)

1) That arrow allows you to run the program
2) You need to click and log in with your Apple ID to use Xcode.

Then after the program starts, you will either be prompted to enter your details or click the top left corner and you'll see preferences

**Comment by Arithemus** [comment]
I am still stuck on how to solve this... What certificates do I need? I have made my account a developer account but I don’t know what to do next. If you could help me that would be appreciated.
