### ISSUE TITLE
Does not always show percentages.

### ISSUE THREAD

**Issue by miles1998** [DanielSmith1239/HQTriviaMaster#49]
For me, on most of the questions, percentages are not shown. It will give me 

0%
100
0% 

or 

--
--
--

**Comment by DanielSmith1239** [comment]
Did you add the api key and search engine Id?

**Comment by miles1998** [comment]
Yes I added everything required under the preferences tab

**Comment by DanielSmith1239** [comment]
Check out the other closed issues, I think I already solved something similar to this.
