### ISSUE TITLE
Getting this error. What gives?

### ISSUE THREAD

**Issue by Arithemus** [DanielSmith1239/HQTriviaMaster#53]
![screen shot 2018-02-27 at 7 53 17 pm](https://user-images.githubusercontent.com/36869480/36765656-ec9821ca-1bf7-11e8-9457-02b4c9ca970c.png)
![screen shot 2018-02-27 at 7 53 08 pm](https://user-images.githubusercontent.com/36869480/36765657-ef08f114-1bf7-11e8-9a8a-4ddb2a92bd31.png)

This comes up when I press run. Anyone have a idea what is wrong? Thanks
*Also I have yet to be asked to put my CSE in and key

**Comment by Arithemus** [comment]
I think the issue is that I have yet to put in my CSE and key. Why is it not asking me to put it in?

**Comment by DanielSmith1239** [comment]
You figure this out?

**Comment by Arithemus** [comment]
No still giving me this error

**Comment by NavkamalBains** [comment]
Having the same error when I try to build the application. Haven't been able to build it so I haven't got the chance to put in my CSE or API.

**Comment by DanielSmith1239** [comment]
possible duplicate of #23
