### ISSUE TITLE
Did not find question end

### ISSUE THREAD

**Issue by IRSAB** [DanielSmith1239/HQTriviaMaster#57]
I have tried using the app a few times, and each time the log
 keeps saying "did not find question end" in the log. Is there a way to fix this?
![screen shot 2018-03-04 at 7 52 11 pm](https://user-images.githubusercontent.com/37057851/36956872-a2006f86-1fe5-11e8-8d62-be74dd2b965c.png)

**Comment by DanielSmith1239** [comment]
Make sure you are capturing the entire question and three options in the screenshot boundary.

**Comment by IRSAB** [comment]
I am doing that, and leaving extra padding around the edges. I have tried multiple sizes and it keep spitting out the same error

**Comment by DanielSmith1239** [comment]
If you can't get the OCR to work, I would recommend just using the web socket. I tested out the OCR and I wasn't running into any issues.
