### ISSUE TITLE
Inconsistent Results

### ISSUE THREAD

**Issue by Eazylikesundaymorning** [DanielSmith1239/HQTriviaMaster#59]
Whenever I rescan a question, I always receive different results. Any ideas what's causing this?

**Comment by parkbroom** [comment]
same issue here

**Comment by Eazylikesundaymorning** [comment]
Found solution - add more websites to search. I seem to get the most accuracy with google, aol, wiki, yippy, dogpile, ecosia, yahoo, duckduckgo, and bing combo
