### ISSUE TITLE
Not able to retrieve questions and answers

### ISSUE THREAD

**Issue by jrudow1** [DanielSmith1239/HQTriviaMaster#6]
@DanielSmith1239 

When I run your program this is the output that I receive back. Basically it is not able to capture the questions and answers.

Mouse Pressed Down
Mouse Released
(69.89453125, 370.7265625, 345.125, 370.1796875)
2018-01-08 20:41:03.333411-0500 HQ Trivia Master[20112:1802995] [Layout] Unable to simultaneously satisfy constraints:
(
    "<NSAutoresizingMaskLayoutConstraint:0x60400008ee20 h=--& v=--& NSBox:0x101214a30'Title'.width == 0   (active)>",
    "<NSAutoresizingMaskLayoutConstraint:0x60400008ec40 h=-&- v=-&- H:[NSView:0x604000121040]-(5.01953)-|   (active, names: '|':NSBox:0x101214a30'Title' )>",
    "<NSAutoresizingMaskLayoutConstraint:0x60400008ebf0 h=-&- v=-&- NSView:0x604000121040.minX == 5.10547   (active, names: '|':NSBox:0x101214a30'Title' )>"
)

Will attempt to recover by breaking constraint 
<NSAutoresizingMaskLayoutConstraint:0x60400008ec40 h=-&- v=-&- H:[NSView:0x604000121040]-(5.01953)-|   (active, names: '|':NSBox:0x101214a30'Title' )>

Set the NSUserDefault NSConstraintBasedLayoutVisualizeMutuallyExclusiveConstraints to YES to have -[NSWindow visualizeConstraints:] automatically called when this happens.  And/or, set a symbolic breakpoint on LAYOUT_CONSTRAINTS_NOT_SATISFIABLE to catch this in the debugger.
2018-01-08 20:41:03.333823-0500 HQ Trivia Master[20112:1802995] [Layout] Unable to simultaneously satisfy constraints:
(
    "<NSAutoresizingMaskLayoutConstraint:0x60400008eec0 h=--& v=--& NSBox:0x101214a30'Title'.height == 0   (active)>",
    "<NSAutoresizingMaskLayoutConstraint:0x60400008ece0 h=-&- v=-&- V:|-(5.40625)-[NSView:0x604000121040]   (active, names: '|':NSBox:0x101214a30'Title' )>",
    "<NSAutoresizingMaskLayoutConstraint:0x60400008ec90 h=-&- v=-&- NSView:0x604000121040.minY == 5.27344   (active, names: '|':NSBox:0x101214a30'Title' )>"
)

Will attempt to recover by breaking constraint 
<NSAutoresizingMaskLayoutConstraint:0x60400008ece0 h=-&- v=-&- V:|-(5.40625)-[NSView:0x604000121040]   (active, names: '|':NSBox:0x101214a30'Title' )>

Set the NSUserDefault NSConstraintBasedLayoutVisualizeMutuallyExclusiveConstraints to YES to have -[NSWindow visualizeConstraints:] automatically called when this happens.  And/or, set a symbolic breakpoint on LAYOUT_CONSTRAINTS_NOT_SATISFIABLE to catch this in the debugger.
env: /usr/local/bin/convert: No such file or directory
Converted .tif: /var/folders/2p/1kcpndps1g5c3p0x20qkm9lc0000gn/T/hqTriviaMasterTemp.tif
env: /usr/local/bin/tesseract: Permission denied

env: /usr/local/bin/convert: No such file or directory
Converted .tif: /var/folders/2p/1kcpndps1g5c3p0x20qkm9lc0000gn/T/hqTriviaMasterTemp.tif
env: /usr/local/bin/tesseract: Permission denied

env: /usr/local/bin/convert: No such file or directory
Converted .tif: /var/folders/2p/1kcpndps1g5c3p0x20qkm9lc0000gn/T/hqTriviaMasterTemp.tif
env: /usr/local/bin/tesseract: Permission denied

env: /usr/local/bin/convert: No such file or directory
Converted .tif: /var/folders/2p/1kcpndps1g5c3p0x20qkm9lc0000gn/T/hqTriviaMasterTemp.tif
env: /usr/local/bin/tesseract: Permission denied

env: /usr/local/bin/convert: No such file or directory
Converted .tif: /var/folders/2p/1kcpndps1g5c3p0x20qkm9lc0000gn/T/hqTriviaMasterTemp.tif
env: /usr/local/bin/tesseract: Permission denied

env: /usr/local/bin/convert: No such file or directory
Converted .tif: /var/folders/2p/1kcpndps1g5c3p0x20qkm9lc0000gn/T/hqTriviaMasterTemp.tif
env: /usr/local/bin/tesseract: Permission denied

env: /usr/local/bin/convert: No such file or directory
Converted .tif: /var/folders/2p/1kcpndps1g5c3p0x20qkm9lc0000gn/T/hqTriviaMasterTemp.tif
env: /usr/local/bin/tesseract: Permission denied

env: /usr/local/bin/convert: No such file or directory
Converted .tif: /var/folders/2p/1kcpndps1g5c3p0x20qkm9lc0000gn/T/hqTriviaMasterTemp.tif
env: /usr/local/bin/tesseract: Permission denied

Mouse Pressed Down
Mouse Released
(73.36328125, 732.046875, 1.49609375, 2.6484375)
Mouse Pressed Down
Mouse Released
(29.2578125, 371.4140625, 337.25, 392.19921875)
env: /usr/local/bin/convert: No such file or directory
Converted .tif: /var/folders/2p/1kcpndps1g5c3p0x20qkm9lc0000gn/T/hqTriviaMasterTemp.tif
env: /usr/local/bin/tesseract: Permission denied

env: /usr/local/bin/convert: No such file or directory
Converted .tif: /var/folders/2p/1kcpndps1g5c3p0x20qkm9lc0000gn/T/hqTriviaMasterTemp.tif
env: /usr/local/bin/tesseract: Permission denied

env: /usr/local/bin/convert: No such file or directory
Converted .tif: /var/folders/2p/1kcpndps1g5c3p0x20qkm9lc0000gn/T/hqTriviaMasterTemp.tif
env: /usr/local/bin/tesseract: Permission denied

env: /usr/local/bin/convert: No such file or directory
Converted .tif: /var/folders/2p/1kcpndps1g5c3p0x20qkm9lc0000gn/T/hqTriviaMasterTemp.tif
env: /usr/local/bin/tesseract: Permission denied

env: /usr/local/bin/convert: No such file or directory
Converted .tif: /var/folders/2p/1kcpndps1g5c3p0x20qkm9lc0000gn/T/hqTriviaMasterTemp.tif
env: /usr/local/bin/tesseract: Permission denied

env: /usr/local/bin/convert: No such file or directory
Converted .tif: /var/folders/2p/1kcpndps1g5c3p0x20qkm9lc0000gn/T/hqTriviaMasterTemp.tif
env: /usr/local/bin/tesseract: Permission denied

env: /usr/local/bin/convert: No such file or directory
Converted .tif: /var/folders/2p/1kcpndps1g5c3p0x20qkm9lc0000gn/T/hqTriviaMasterTemp.tif
env: /usr/local/bin/tesseract: Permission denied

env: /usr/local/bin/convert: No such file or directory
Converted .tif: /var/folders/2p/1kcpndps1g5c3p0x20qkm9lc0000gn/T/hqTriviaMasterTemp.tif
env: /usr/local/bin/tesseract: Permission denied

**Comment by jrudow1** [comment]
@DanielSmith1239 @schlossm 

can you please advise how to fix the error above.

**Comment by schlossm** [comment]
So there’s quite a few issues I’m seeing here.

- First, you can safely ignore those constraint errors.  That’s just macOS being weird with NSBox’s (it doesn’t like them not having titles sometimes
- Second, “env: /usr/local/bin/convert: No such file or directory”.  This means you don’t have Tesseract installed.  You can do this by opening Terminal, and running `brew install tesseract`

Just install tesseract and you shouldn’t have anymore issues with questions not being retrieved!

**Comment by jrudow1** [comment]
@schlossm I do have tesseract installed though.

I even went as far as uninstalling it and reinstalling it again and I am still having the same problem.

**Comment by schlossm** [comment]
Hi @jrudow1,

Do you have System Integrity Protection enabled? You can check by running `csrutil status` in Terminal.  I had it disabled on my Mac, and once I enabled it, `/usr/local/bin/convert` was removed and cannot be reinstalled until SIP is disabled again.

Also, please verify that App Sandbox is disabled in your Xcode Project under Capabilities.  If the sandbox is enabled, the app does not have access to `tesseract` or `convert`

**Comment by schlossm** [comment]
@jrudow1, during more testing on your issue, I found out that the `convert` tool is from a different package.  You will also need to install [ImageMagick](https://www.imagemagick.org/script/download.php) or in Terminal with `brew install imagemagick`

**Comment by jrudow1** [comment]
@schlossm 

I checked SIP and it is enabled. I also just checked about App Sandbox and it is turned off.

I also just installed ImageMagick.

I am still getting this error

Mouse Pressed Down
Mouse Released
(70.69140625, 376.140625, 340.50390625, 369.65625)
2018-01-09 18:34:54.910528-0500 HQ Trivia Master[23364:2128534] [Layout] Unable to simultaneously satisfy constraints:
(
    "<NSAutoresizingMaskLayoutConstraint:0x60800008a8c0 h=--& v=--& NSBox:0x101432460'Title'.width == 0   (active)>",
    "<NSAutoresizingMaskLayoutConstraint:0x60800008a6e0 h=-&- v=-&- H:[NSView:0x608000121a40]-(5.19531)-|   (active, names: '|':NSBox:0x101432460'Title' )>",
    "<NSAutoresizingMaskLayoutConstraint:0x60800008a690 h=-&- v=-&- NSView:0x608000121a40.minX == 5.30859   (active, names: '|':NSBox:0x101432460'Title' )>"
)

Will attempt to recover by breaking constraint 
<NSAutoresizingMaskLayoutConstraint:0x60800008a6e0 h=-&- v=-&- H:[NSView:0x608000121a40]-(5.19531)-|   (active, names: '|':NSBox:0x101432460'Title' )>

Set the NSUserDefault NSConstraintBasedLayoutVisualizeMutuallyExclusiveConstraints to YES to have -[NSWindow visualizeConstraints:] automatically called when this happens.  And/or, set a symbolic breakpoint on LAYOUT_CONSTRAINTS_NOT_SATISFIABLE to catch this in the debugger.
2018-01-09 18:34:54.910803-0500 HQ Trivia Master[23364:2128534] [Layout] Unable to simultaneously satisfy constraints:
(
    "<NSAutoresizingMaskLayoutConstraint:0x60800008a960 h=--& v=--& NSBox:0x101432460'Title'.height == 0   (active)>",
    "<NSAutoresizingMaskLayoutConstraint:0x60800008a780 h=-&- v=-&- V:|-(5.29688)-[NSView:0x608000121a40]   (active, names: '|':NSBox:0x101432460'Title' )>",
    "<NSAutoresizingMaskLayoutConstraint:0x60800008a730 h=-&- v=-&- NSView:0x608000121a40.minY == 5.35938   (active, names: '|':NSBox:0x101432460'Title' )>"
)

Will attempt to recover by breaking constraint 
<NSAutoresizingMaskLayoutConstraint:0x60800008a780 h=-&- v=-&- V:|-(5.29688)-[NSView:0x608000121a40]   (active, names: '|':NSBox:0x101432460'Title' )>

Set the NSUserDefault NSConstraintBasedLayoutVisualizeMutuallyExclusiveConstraints to YES to have -[NSWindow visualizeConstraints:] automatically called when this happens.  And/or, set a symbolic breakpoint on LAYOUT_CONSTRAINTS_NOT_SATISFIABLE to catch this in the debugger.
Converted .tif: /var/folders/2p/1kcpndps1g5c3p0x20qkm9lc0000gn/T/hqTriviaMasterTemp.tif
env: /usr/local/bin/tesseract: Permission denied

Converted .tif: /var/folders/2p/1kcpndps1g5c3p0x20qkm9lc0000gn/T/hqTriviaMasterTemp.tif
env: /usr/local/bin/tesseract: Permission denied

Converted .tif: /var/folders/2p/1kcpndps1g5c3p0x20qkm9lc0000gn/T/hqTriviaMasterTemp.tif
env: /usr/local/bin/tesseract: Permission denied

Converted .tif: /var/folders/2p/1kcpndps1g5c3p0x20qkm9lc0000gn/T/hqTriviaMasterTemp.tif
env: /usr/local/bin/tesseract: Permission denied

Converted .tif: /var/folders/2p/1kcpndps1g5c3p0x20qkm9lc0000gn/T/hqTriviaMasterTemp.tif
env: /usr/local/bin/tesseract: Permission denied

Converted .tif: /var/folders/2p/1kcpndps1g5c3p0x20qkm9lc0000gn/T/hqTriviaMasterTemp.tif
env: /usr/local/bin/tesseract: Permission denied

Converted .tif: /var/folders/2p/1kcpndps1g5c3p0x20qkm9lc0000gn/T/hqTriviaMasterTemp.tif
env: /usr/local/bin/tesseract: Permission denied

Converted .tif: /var/folders/2p/1kcpndps1g5c3p0x20qkm9lc0000gn/T/hqTriviaMasterTemp.tif
env: /usr/local/bin/tesseract: Permission denied

Converted .tif: /var/folders/2p/1kcpndps1g5c3p0x20qkm9lc0000gn/T/hqTriviaMasterTemp.tif
env: /usr/local/bin/tesseract: Permission denied

Converted .tif: /var/folders/2p/1kcpndps1g5c3p0x20qkm9lc0000gn/T/hqTriviaMasterTemp.tif
env: /usr/local/bin/tesseract: Permission denied

**Comment by schlossm** [comment]
Can you verify if the issue "env: /usr/local/bin/tesseract: Permission denied" still persists if you disable SIP? You can disable it by booting into Recovery (⌘ + R) and running `csrutil disable` in Terminal

**Comment by jrudow1** [comment]
This is when SIP is disabled

Mouse Pressed Down
Mouse Released
(74.37890625, 375.29296875, 337.95703125, 362.3359375)
2018-01-09 20:31:04.408251-0500 HQ Trivia Master[735:9500] [Layout] Unable to simultaneously satisfy constraints:
(
    "<NSAutoresizingMaskLayoutConstraint:0x60000008ad70 h=--& v=--& NSBox:0x101211f40'Title'.width == 0   (active)>",
    "<NSAutoresizingMaskLayoutConstraint:0x60000008ab90 h=-&- v=-&- H:[NSView:0x6000001210e0]-(5.33594)-|   (active, names: '|':NSBox:0x101211f40'Title' )>",
    "<NSAutoresizingMaskLayoutConstraint:0x60000008ab40 h=-&- v=-&- NSView:0x6000001210e0.minX == 5.12109   (active, names: '|':NSBox:0x101211f40'Title' )>"
)

Will attempt to recover by breaking constraint 
<NSAutoresizingMaskLayoutConstraint:0x60000008ab90 h=-&- v=-&- H:[NSView:0x6000001210e0]-(5.33594)-|   (active, names: '|':NSBox:0x101211f40'Title' )>

Set the NSUserDefault NSConstraintBasedLayoutVisualizeMutuallyExclusiveConstraints to YES to have -[NSWindow visualizeConstraints:] automatically called when this happens.  And/or, set a symbolic breakpoint on LAYOUT_CONSTRAINTS_NOT_SATISFIABLE to catch this in the debugger.
2018-01-09 20:31:04.408688-0500 HQ Trivia Master[735:9500] [Layout] Unable to simultaneously satisfy constraints:
(
    "<NSAutoresizingMaskLayoutConstraint:0x60000008ae10 h=--& v=--& NSBox:0x101211f40'Title'.height == 0   (active)>",
    "<NSAutoresizingMaskLayoutConstraint:0x60000008ac30 h=-&- v=-&- V:|-(5.12891)-[NSView:0x6000001210e0]   (active, names: '|':NSBox:0x101211f40'Title' )>",
    "<NSAutoresizingMaskLayoutConstraint:0x60000008abe0 h=-&- v=-&- NSView:0x6000001210e0.minY == 5.20703   (active, names: '|':NSBox:0x101211f40'Title' )>"
)

Will attempt to recover by breaking constraint 
<NSAutoresizingMaskLayoutConstraint:0x60000008ac30 h=-&- v=-&- V:|-(5.12891)-[NSView:0x6000001210e0]   (active, names: '|':NSBox:0x101211f40'Title' )>

Set the NSUserDefault NSConstraintBasedLayoutVisualizeMutuallyExclusiveConstraints to YES to have -[NSWindow visualizeConstraints:] automatically called when this happens.  And/or, set a symbolic breakpoint on LAYOUT_CONSTRAINTS_NOT_SATISFIABLE to catch this in the debugger.
Converted .tif: /var/folders/2p/1kcpndps1g5c3p0x20qkm9lc0000gn/T/hqTriviaMasterTemp.tif
env: /usr/local/bin/tesseract: Permission denied
Error Domain=NSCocoaErrorDomain Code=260 "The file “output.txt” couldn’t be opened because there is no such file." UserInfo={NSFilePath=/var/folders/2p/1kcpndps1g5c3p0x20qkm9lc0000gn/T/output.txt, NSUnderlyingError=0x60c000058990 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}

**Comment by schlossm** [comment]
Does your user account have access to `/usr/local/bin/tesseract`?  That's about the only thing I can think of left that could be wrong with tesseract

**Comment by jrudow1** [comment]
@schlossm 

When I go to that file path I see it and I am able to get into it.

I also checked the permissions and I have read and write permissions

**Comment by lylewaranch** [comment]
I was getting the exact same errors as @jrudow1 and I fixed it by installing ImageMagick.

**Comment by jrudow1** [comment]
@schlossm I got it to work after I re enabled SIP and then uninstalled tesseract and then installed it again

**Comment by schlossm** [comment]
I'm glad to hear it!

**Comment by jrudow1** [comment]
The algorithms do need to be updated though because it got quite a few questions wrong tonight

**Comment by schlossm** [comment]
+1.  It's something I'm silently working on but it takes a lot of research into the search results, and will most likely require leveraging some sort of neural network in the future.  Pull Request #9 implements a better answering system in which it'll give your the percentage probability for each answer.

**Comment by jrudow1** [comment]
@schlossm how can I install your pull request to update what I currently have?

**Comment by lylewaranch** [comment]
@jrudow1 He hasn't merged it yet.

**Comment by schlossm** [comment]
@jrudow1 @lylewaranch 

It won't be merged for about a week since Daniel is busy.  So right now the only way to do it is to actually visit my fork and download it from there.  Or, you could wait a week for the changes to be merged and update directly from here

**Comment by jrudow1** [comment]
@schlossm I have a suggestion for the next part of this program that you are currently making.

I suggest that at some point have it start to a degree to self learn and correct when it sees that it got a question wrong it records that question and the correct answer so if it ever comes up again or something similar it will give the correct answer. So basically building in an AI
