### ISSUE TITLE
Nothing on mitmproxy after opening HQ Trivia on iPhone.,

### ISSUE THREAD

**Issue by smartkidag** [DanielSmith1239/HQTriviaMaster#61]
I've installed everything and added mitmproxy server to my iPhone. When I open HQTrivia on my phone, I can see nothing under flows in mitmproxy. What's the problem?

**Comment by Eazylikesundaymorning** [comment]
Go to settings, general, certificate trust settings, and trust it. Probably your issue

**Comment by Alex63908** [comment]
this didn't work for me
