### ISSUE TITLE
Other Uses

### ISSUE THREAD

**Issue by Eazylikesundaymorning** [DanielSmith1239/HQTriviaMaster#63]
<img width="1280" alt="screen shot 2018-03-08 at 12 12 31 am" src="https://user-images.githubusercontent.com/36711729/37136025-704b95ec-2265-11e8-86db-d1c86c8fde0c.png">

If I wanted to use this for another trivia app, could I use websocket and enter "device token" and it would work as my token etc.?

**Comment by DanielSmith1239** [comment]
You would need to alter the code a bit more, specifically the connection controller and socket manager to connect to the specific app.

**Comment by unknown110** [comment]
Hi @DanielSmith1239 , if I only use the OCR, would I need to alter the connection controller and the socket manager to connect to the specific app? And would you be able to give a quick guide on how to alter these 2 things? I'm interested in learning but have no coding experience.
