### ISSUE TITLE
let url = URL(string: "https://api-quiz.hype.space/shows/now?type=hq&userId=\(credentials.username ?? "")")!

### ISSUE THREAD

**Issue by hithlo** [DanielSmith1239/HQTriviaMaster#66]
Says Thread 1: Fatal error: Unexpectedly found nil while unwrapping an Optional value. Any way of fixing it 
![screen shot 2018-03-09 at 7 11 15 pm](https://user-images.githubusercontent.com/37162282/37235593-c4821424-23cd-11e8-891e-9d3ed5d8c7c8.png)

**Comment by DanielSmith1239** [comment]
There is an issue with your token. Are you sure you put it in?

**Comment by hithlo** [comment]
I cant build the program, so I can't put in the token.

**Comment by hithlo** [comment]
Nvm I fixed it. Thank you so much
