### ISSUE TITLE
Probability 100%

### ISSUE THREAD

**Issue by NavkamalBains** [DanielSmith1239/HQTriviaMaster#69]
Not sure if it's the sites I added to my google cse or if im inputting it wrong but I keep getting 100% for one answer and zero for the other ones and only 1 result is popping up. What sites should I add to my google cse? Also is the search engine id the entire number including the semicolon (:) or is it just one part of it?

example:

Answers:
Hearst Tower: 0
One Vanderbilt: 0
30 Rockefeller Plaza: 1
Predicted Correct Answer: 30 Rockefeller Plaza

**Comment by NavkamalBains** [comment]
Also wanted to add that the 100% probability is completely false. The answer is incorrect 80% of the time for the answer it gives you.

**Comment by DanielSmith1239** [comment]
You probably didn’t configure it correctly. I got out on question 11 yesterday.

**Comment by DanielSmith1239** [comment]
See #33.

**Comment by DanielSmith1239** [comment]
You need to put in the entire key...

**Comment by NavkamalBains** [comment]
In your google cse settings, under sites to search, do you have it set to search the entire web but emphasize included sites? Updated my search engine id and api's and i'll let you know if anything changes or not.

**Comment by NavkamalBains** [comment]
Also when I create a custom search engine, i'm not receiving any link to verify it as it says in your instructions.

**Comment by NavkamalBains** [comment]
Got it working! Got to Q9 with it right now. Any sites you'd recommend me to add to the sites to search list before you resolve this issue?

**Comment by DanielSmith1239** [comment]
What sites do you have right now?

**Comment by NavkamalBains** [comment]
Google, Bing, Yahoo, duckduckgo, wikipedia, oxford english dictionary, genius (for questions about song lyrics), imdb (for questions about movies), wolfram alpha (for math questions), and britannica.

Suggestions on what to remove/add to improve accuracy? I feel like im getting 65-70% accuracy right now.

**Comment by DanielSmith1239** [comment]
That seems like a bit much. Someone just opened an issue for talking about the search engines, so post this in that question. I’ll close this one.
