### ISSUE TITLE
Mach-O Linker Error

### ISSUE THREAD

**Issue by ethancplatt** [DanielSmith1239/HQTriviaMaster#7]
I can only succesfully build it in xcworkspace but when scanning for the question it says Error in fopenReadStream: file not found. When building in xcproj I get an Apple Mach-O Linker (id) Error: linker command failed with exit code 1 (use -v to see invocation)
Thanks for the Help,
Ethan

**Comment by jrudow1** [comment]
@ethancplatt I had the same problem I was able to fix that by going into the folder form terminal and then doing the command pod install.

**Comment by CJerome5** [comment]
@ethancplatt can I add you on skype or discord? I’m a little confused about this.

**Comment by ethancplatt** [comment]
@CJerome5 yes you can add me on discord: EDog2102 #6405

**Comment by ethancplatt** [comment]
@jrudow1 i have already ran pod install on it. the linker error comes from Pods_HQ_Trivia_Master.framework, which is under frameworks

**Comment by CJerome5** [comment]
@jrudow1 Can I add you on skype or discord? I’m a little confused how you got it to work

**Comment by schlossm** [comment]
You can only build in the `xcworkspace` file, building from the HQTriviaMaster `xcodeproj` file will **not** work due to PODS requirements.

@ethancplatt can you paste the Xcode Terminal output so I can see the log?

**Comment by ethancplatt** [comment]
@schlossm here is the Xcode Terminal output what should I do?: 

Set the NSUserDefault NSConstraintBasedLayoutVisualizeMutuallyExclusiveConstraints to YES to have -[NSWindow visualizeConstraints:] automatically called when this happens.  And/or, set a symbolic breakpoint on LAYOUT_CONSTRAINTS_NOT_SATISFIABLE to catch this in the debugger.
env: /usr/local/bin/convert: Permission denied
Converted .tif: /var/folders/5t/b_p_zln148x7jy0c_7mrfxc80000gn/T/hqTriviaMasterTemp.tif
Tesseract Open Source OCR Engine v3.05.01 with Leptonica
Error in fopenReadStream: file not found
Error in findFileFormat: image file not found
Error during processing.

**Comment by schlossm** [comment]
It looks like you haven't installed `ImageMagick`.  Try installing that and that should resolve the issue you're having

**Comment by ethancplatt** [comment]
@schossm i installed image magick using "sudo port install ImageMagick" but i still get the error:

Set the NSUserDefault NSConstraintBasedLayoutVisualizeMutuallyExclusiveConstraints to YES to have -[NSWindow visualizeConstraints:] automatically called when this happens.  And/or, set a symbolic breakpoint on LAYOUT_CONSTRAINTS_NOT_SATISFIABLE to catch this in the debugger.
Mouse Pressed Down
Mouse Released
(98.62109375, 298.16796875, 349.77734375, 338.87890625)
env: /usr/local/bin/convert: Permission denied
Converted .tif: /var/folders/5t/b_p_zln148x7jy0c_7mrfxc80000gn/T/hqTriviaMasterTemp.tif
Tesseract Open Source OCR Engine v3.05.01 with Leptonica
Error in fopenReadStream: file not found
Error in findFileFormat: image file not found
Error during processing.

**Comment by schlossm** [comment]
Can you verify that `/usr/local/bin/convert` exists?

**Comment by ethancplatt** [comment]
@schlossm i created my own convert file in /usr/local/bin/, because it didn't exist

**Comment by schlossm** [comment]
ImageMagick should have a `convert` file.  You will need to alias it from wherever MacPorts installed it.  After that, you shouldn't have any issues.

`sudo ln -sf /path/to/macports/imagemagick/location/convert /usr/local/bin/convert`

**Comment by ethancplatt** [comment]
@schlossm ok thanks so much for the help I will try that and respond if it works

**Comment by ethancplatt** [comment]
@schlossm i know have a thing called convert but when i open it, it opens a terminal window saying:

Ethans-MacBook-Air-2:~ ethanplatt$ /usr/local/Cellar/imagemagick/7.0.7-21/bin/magick ; exit;
Error: Invalid argument or not enough arguments

Usage: magick tool [ {option} | {image} ... ] {output_image}
Usage: magick [ {option} | {image} ... ] {output_image}
       magick [ {option} | {image} ... ] -script {filename} [ {script_args} ...]
       magick -help | -version | -usage | -list {option}

logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[Process completed]

**Comment by schlossm** [comment]
`/usr/local/Cellar/imagemagick/7.0.7-21/bin/convert` <- That is the full file path to convert following your path given. so, if you run 

`sudo ln -sf /usr/local/Cellar/imagemagick/7.0.7-21/bin/convert /usr/local/bin/convert`

that should fully resolve the issue and should work when you run HQTriviaMaster.  The `magick` script isn't used

**Comment by ethancplatt** [comment]
@schlossm ok now i have it putting the questions and answers in but it is giving me the wrong answer, because it isn't searching, this is the output:

Page 1
Canon, Nikon, and Olympus all
specialize in what products?

Can openers
Cameras

Candelabras


Question type: Middle What
Question search function code: 14

Answers:
Cameras: 0
Can openers: 0
Candelabras: 0
Predicted Correct Answer: Candelabras

**Comment by schlossm** [comment]
You'll need to put in your Google CSE API Key and Search Engine ID into the `SiteEncoding.swift` file

**Comment by ethancplatt** [comment]
@schlossm i did, does this mean they are bad keys and ID's

**Comment by ethancplatt** [comment]
@schlossm i created a new API Key and Search Engine ID but when I run the program it is only gets half the questions right, what is the optimal website to search, at the moment i have wikepedia and google.

**Comment by schlossm** [comment]
The bot isn't guaranteed to get every question right.  It's the unfortunate reality of a bot such as this one (ones not built on top of strong, highly trained neural networks).  While we're for sure trying to improve the accuracy of results, it's a hard thing to do that'll take time.  I'm sorry for the inconvenience in it, I myself wish I could stick a human encyclopedia into it and get every question right.

As for websites you can use, I'd say as many different sources and you can put into it.  The more information the bot can receive from the search results, the higher the chance it'll make the right the right decision
