### ISSUE TITLE
I am getting this issue

### ISSUE THREAD

**Issue by elliot347** [DanielSmith1239/HQTriviaMaster#71]
<img width="267" alt="screen shot 2018-03-13 at 11 51 00 am" src="https://user-images.githubusercontent.com/37338990/37353027-db4c1350-26b4-11e8-9b9f-88b255ce8a13.png">
can you help me fix it

**Comment by DanielSmith1239** [comment]
Please check the previous issues before posting new ones, I believe this has already been answered.
