### ISSUE TITLE
Final issue, i promise,

### ISSUE THREAD

**Issue by elliot347** [DanielSmith1239/HQTriviaMaster#72]
<img width="1138" alt="screen shot 2018-03-13 at 12 27 19 pm" src="https://user-images.githubusercontent.com/37338990/37355341-e31a0204-26b9-11e8-9545-c32e71e57969.png">
I don't know how to fix this error and I could not find a repeat of it anywhere

**Comment by DanielSmith1239** [comment]
If you follow the instructions, you won’t have this problem.
