### ISSUE TITLE
Scanning the Questions with OCR

### ISSUE THREAD

**Issue by unknown110** [DanielSmith1239/HQTriviaMaster#75]
So with tesseract, is the bot scanning specific areas of the screen and determining which part of the screen is the questions and which part is answers?

**Comment by DanielSmith1239** [comment]
Nope. You hit the “Define Boundry” and tell the program where to scan.

**Comment by unknown110** [comment]
so what i'm curious about is how does it know which words are part of the question and when does it end and the words become the options? @DanielSmith1239

**Comment by DanielSmith1239** [comment]
Magic lol. Looks for the question mark, and after that the options are separated by a new line.

**Comment by DanielSmith1239** [comment]
That’s the jist of it, check out the code for more details.

**Comment by unknown110** [comment]
where in the code is it? like which section?

**Comment by DanielSmith1239** [comment]
I think it’s in the view controller
