### ISSUE TITLE
Support for 4 Options & Other languages?

### ISSUE THREAD

**Issue by tokyoghoul6** [DanielSmith1239/HQTriviaMaster#78]
First of all, really thank you for your amazing work. I have some request you might want to consider.

There are some trivia games that give 4 options instead of 3, unlike HQ Trivia. So, I was wondering if you can also add a column for 4 option and give an option to enable it from the Preferences?

Also, is it possible that it will work with the app that has different language? 

Thanks.

**Comment by DanielSmith1239** [comment]
I don’t really have time to work on this, but feel free to submit a PR!
