### ISSUE TITLE
No Hq Trivia Master.app

### ISSUE THREAD

**Issue by apates5** [DanielSmith1239/HQTriviaMaster#8]
Trying to look for the .app file but it seems to not be there. Do I have to create it in Xcode?

**Comment by schlossm** [comment]
Hi @apates5,

Yea you've got to open it in Xcode and build the app.  Follow the directions in the README for all the other dependencies and information you'll need to make the app work!

Thanks

**Comment by apates5** [comment]
G
![screen shot 2018-01-09 at 7 35 11 pm](https://user-images.githubusercontent.com/31677811/34751801-5148f428-f574-11e7-81a6-9c3995fbbbe2.png)
ot this error. How can I fix it?

**Comment by schlossm** [comment]
What does the Editor say when you click on "Linker command failed…"?

**Comment by apates5** [comment]
this comes up
![screen shot 2018-01-09 at 9 33 58 pm](https://user-images.githubusercontent.com/31677811/34754699-f145b050-f584-11e7-8499-2bc51b913fed.png)

**Comment by schlossm** [comment]
You'll need to run `pod install` in Terminal while in the Xcode Project's directory.  Or, you can checkout Pull Request #9 which removes the Pods requirements as they're unused
