### ISSUE TITLE
Completely Wrong Answers

### ISSUE THREAD

**Issue by setivega** [DanielSmith1239/HQTriviaMaster#80]
I don't know if my Custom Search Engine is activated because I don't know where to find the link as mentioned in the instrucitons. If it isn't how would I got about making it work.

<img width="747" alt="screen shot 2018-03-21 at 9 45 34 am" src="https://user-images.githubusercontent.com/29467347/37713367-158a017e-2ced-11e8-8ba8-e253b0d95a5c.png">

**Comment by DanielSmith1239** [comment]
lol
