### ISSUE TITLE
Parts of questions ending up in the options field? 

### ISSUE THREAD

**Issue by levilucasmusic** [DanielSmith1239/HQTriviaMaster#83]
Hello! I got this project up and running earlier but I have one small hiccup. 

If the question is displayed in two lines, HQ Trivia Master will input the question correctly, but will also use the second line of the question as option one. Of course, this means one of the actual options doesn’t get inputted and throws off the probabilities. 
I messed around with the defined boundaries a bit but that didn’t seem to change it.
Any ideas?

**Comment by levilucasmusic** [comment]
I'm actually getting a fatal error for Option 2, saying "Thread 1: Fatal error: Can't remove last element from an empty collection"
So with each question, it isn't finding an Option 2 so its using part of the question to fill in Option 1, and Option 1 to fill in Option 2.
Any ideas on a fix?

**Comment by jolbol1** [comment]
Noticed similar, OCR will never be as good as WebSocket which I highly recommend using instead.

**Comment by levilucasmusic** [comment]
Yeah for sure! I was just using the ocr for other trivia games like cash show, because I’m not sure how to use the websocket for them. Any ideas how?

**Comment by jolbol1** [comment]
Afraid not, I tried to do it myself, I know how to code just know nothing about web sockets lol

**Comment by DanielSmith1239** [comment]
@levilucasmusic make sure you're capturing the entire question and all three options.
@jolbol1 I didn't know much about web sockets either before making this, you just need to play around with it.

**Comment by levilucasmusic** [comment]
Yeah I had them all covered! Like I said I tried to play around with the defined boundaries a bit to see if it was tesseract being goofy. To no avail though.
