### ISSUE TITLE
Issues/Improvements with the CSE and chances for each answer???

### ISSUE THREAD

**Issue by Kev9200** [DanielSmith1239/HQTriviaMaster#91]
So when I have my CSE set up, under "Sites to Search", should the scroll down be "Search the entire web but emphasize included sites" or "search only included sites"? The entire web search gives out the exact percent number for each answer while the only included websites give two of the answers "0%" and one answer "100%." Sometimes the highest percentage is not the correct answer and I'm trying to figure out what web searches/engines I should add to improve the accuracy to at least 95%.
These are the sites I have:
https://www.wolframalpha.com/
https://www.wikipedia.org/
https://scholar.google.com/

And even with these sites, the percent or the number of the answer does not change, only how the answer should be searched takes affect.

**Comment by DanielSmith1239** [comment]
There is already a discussion post dedicated to this...

**Comment by Kev9200** [comment]
@DanielSmith1239 what number because it doesn’t answer all my questions?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
