### ISSUE TITLE
Can't open HQTriviaMaster.xcworkspace

### ISSUE THREAD

**Issue by gh5409** [DanielSmith1239/HQTriviaMaster#98]
After successfully downloading the pods, I tried to open HQTriviaMaster.xcworkspace, where a file pops up from terminal but it doesn't build or give me any prompt. Help?

**Comment by shreystechtips** [comment]
do you have xcode installed?

**Comment by gh5409** [comment]
Ah, thank you! @shreystechtips

**Comment by shreystechtips** [comment]
No problem!

**Comment by spaz926** [comment]
@DanielSmith1239 can be closed.
